"""edge_rust.run against production R on small designs the corpus does not cover.

Corpus-free: every input and reference lives in ``tests/edger_cases/<case>/``, generated by
``generate.R`` from MDFlexiComparisons ``runEdgeRPairwiseStats`` in the md-flexi-r45-local image
(edgeR 4.8.2). ``gap_zero`` and ``gap_tiny`` put df.prior inside (3, 50) with 3% of genes at
df.residual.adj = 0 and 3.4% at 0 < df.residual.adj < 0.01 (review r1, stats e); the rest are the
review's adversarial "matches edgeR" cases (empty group, singleton group, 1 residual df, 1 to 4
genes, dispersion capped at 4, zero groups with and without controls, sparse RLE and
upperquartile input). ``k_lib*_none`` (one sample with a library of 1 to 5 counts, norm none)
and ``thin*_tmm`` (one sample of the corpus count_synth case thinned to 100 or 1,000 counts)
make a one-group fit miss convergence in estimateDisp, where edgeR reuses the last written
gene's coefficient (review overnight r1, M1); ``k_lib1_reid_none`` renames the stalled gene so
that its numeric and bytewise predecessors differ (review overnight r2, Minor 1). Inputs come from
``make_gap_inputs.R``, ``make_k_lib_inputs.py`` and ``make_thin_inputs.R``.
"""

from __future__ import annotations

import json
from pathlib import Path

import edge_rust
import numpy as np
import pandas as pd
import pytest

CASES_DIR = Path(__file__).parent / "edger_cases"
CASES = sorted(p.name for p in CASES_DIR.iterdir() if (p / "reference_output.csv").exists())
TOL = 1e-8


def load(case: str):
    d = CASES_DIR / case
    counts = pd.read_csv(d / "input_counts.csv", dtype={"id": str}).set_index("id")
    si = pd.read_csv(d / "input_sample_info.csv", dtype={"replicate": str, "condition": str})
    cmp = pd.read_csv(d / "input_comparisons.csv", dtype=str)
    params = json.loads((d / "params.json").read_text())
    return counts, si, cmp, params


def close(name: str, got: np.ndarray, want: np.ndarray, floor=0.0):
    na_g, na_w = np.isnan(got), np.isnan(want)
    assert (na_g == na_w).all(), f"{name}: NA pattern differs at {np.flatnonzero(na_g != na_w)[:5]}"
    a, b = got[~na_w], want[~na_w]
    if np.ndim(floor):
        floor = floor[~na_w]
    ok = np.abs(a - b) <= TOL * np.maximum(np.abs(b), floor)
    assert ok.all(), f"{name}: {a[~ok][:3]} vs {b[~ok][:3]}"


def test_cases_exist():
    assert {
        "gap_zero",
        "gap_tiny",
        "singleton",
        "zerogroup",
        "df1",
        "dispcap",
        "k_lib1_one_gene_none",
        "k_lib2_one_gene_none",
        "k_lib5_one_gene_none",
        "k_lib1_rle_nogene_none",
        "k_lib1_reid_none",
        "thin100_tmm",
        "thin1000_tmm",
    } <= set(CASES)


def close_p(name: str, got: np.ndarray, want: np.ndarray):
    na_g, na_w = np.isnan(got), np.isnan(want)
    assert (na_g == na_w).all(), f"{name}: NA pattern differs at {np.flatnonzero(na_g != na_w)[:5]}"
    a, b = got[~na_w], want[~na_w]
    scale = np.maximum(1.0, np.abs(np.log(np.maximum(b, 1e-300))))
    ok = np.abs(a - b) <= TOL * np.abs(b) * scale
    assert ok.all(), f"{name}: {a[~ok][:3]} vs {b[~ok][:3]}"


@pytest.mark.parametrize("case", CASES)
def test_table_matches_production(case):
    counts, si, cmp, params = load(case)
    got = edge_rust.run(counts, si, cmp, params)
    want = pd.read_csv(CASES_DIR / case / "reference_output.csv")
    # runEdgeRPairwiseStats returns C-collation order; the port keeps the input row order, as
    # runDiscovery's final table follows the features metadata.
    pos = {g: i for i, g in enumerate(counts.index)}
    want = want.iloc[np.argsort([pos[str(g)] for g in want["GroupId"]], kind="stable")]
    want = want.reset_index(drop=True)
    assert list(got.columns) == list(want.columns)
    assert (got["GroupId"].to_numpy() == want["GroupId"].to_numpy()).all()
    for c in want.columns[1:]:
        stat, _, label = c.partition(" ")
        g, w = got[c].to_numpy(dtype=float), want[c].to_numpy(dtype=float)
        fcol = "F" + (f" {label}" if label else "")
        f_g, f_w = got[fcol].to_numpy(dtype=float), want[fcol].to_numpy(dtype=float)
        if stat in ("stat", "SE", "CILeft", "CIRight"):
            # Production's NA rule, usable = is.finite(F) & F > 0 (edgeRStatsFun.R:252), holds
            # on the port's own F, and the NA pattern matches R's exactly except on rows where F
            # is rounding noise around 0 on both sides with opposite signs, so the same rule
            # lands on different sides of 0 (review r2, R2-4).
            use_g, use_w = np.isfinite(f_g) & (f_g > 0), np.isfinite(f_w) & (f_w > 0)
            assert (np.isnan(g) | use_g).all(), f"{case} {c}: a value where F is not usable"
            if stat == "stat":
                assert (np.isnan(g) == ~use_g).all(), f"{case} {c}: NA where F is usable"
            flip = use_g != use_w
            noise = (np.abs(f_g) < 1e-10) & (np.abs(f_w) < 1e-10)
            assert noise[flip].all(), f"{case} {c}: F usable on one side only at {f_w[flip]}"
            same = np.isnan(g[~flip]) == np.isnan(w[~flip])
            assert same.all(), f"{case} {c}: NA pattern differs at {np.flatnonzero(~same)[:5]}"
        if stat in ("stat", "SE", "CILeft", "CIRight", "PValue", "AdjPValue"):
            # sqrt(F) carries half the relative error of F, and F below 1e-4 is checked at 1e-8
            # absolute (gaps there are ~1e-13, rounding noise around 0 on both sides, which a
            # 1-df p-value near 1 turns into ~1e-7), so the derived values are compared where
            # F >= 1e-4; p is still checked below it, at 1e-6 absolute.
            keep = ~(np.abs(f_w) < 1e-4)
            if stat in ("PValue", "AdjPValue"):
                lo_g, lo_w = g[~keep], w[~keep]
                assert (np.isnan(lo_g) == np.isnan(lo_w)).all(), f"{case} {c}: NA pattern, F < 1e-4"
                gap = np.abs(lo_g - lo_w)[~np.isnan(lo_w)]
                assert (gap <= 1e-6).all(), f"{case} {c}: p gap {gap.max():.3g} where F < 1e-4"
            g, w = g[keep], w[keep]
        if stat in ("PValue", "AdjPValue"):
            # The tail gap comes from df.prior, not F: df.prior differs from R by up to 1.6e-9
            # relative (gated directly at 1e-8 in test_df_matches_production) and
            # |d ln p / d ln df2| is 18-35 at p < 1e-30. Gated at 1e-8 * max(1, |ln p|), 11x
            # above the worst gap (review r2, R2-3).
            close_p(f"{case} {c}", g, w)
            continue
        floor = 1.0 if stat == "F" else 0.0
        if stat in ("CILeft", "CIRight"):
            # Log2FC -/+ q SE cancels near 0; the error lives in the half-width q SE.
            hw = (want[f"CIRight {label}"] - want[f"CILeft {label}"]).to_numpy(dtype=float) / 2
            floor = hw[keep]
        close(f"{case} {c}", g, w, floor=floor)


@pytest.mark.parametrize("case", CASES)
def test_df_matches_production(case):
    counts, si, cmp, params = load(case)
    diag_csv = CASES_DIR / case / "r_diag.csv"
    if not diag_csv.exists():
        # k_lib1_reid_none's table came from a logged production run; its r_diag.csv waits for
        # the next generate.R run (overnight fix round 2: the oracle was unavailable).
        pytest.skip(f"{case}: no r_diag.csv yet")
    _, diag = edge_rust.run(counts, si, cmp, params, diagnostics=True)
    want = pd.read_csv(diag_csv, dtype={"id": str}).set_index("id")
    genes = diag["genes"]
    ids = list(genes["id"].astype(str))
    assert sorted(ids) == sorted(want.index)
    want = want.loc[ids]
    close(f"{case} df_prior", genes["df_prior"].to_numpy(), want["df_prior"].to_numpy())
    # df.residual.adj = 0 exactly where R has it, and within 1e-8 of 1 elsewhere.
    got_adj, want_adj = genes["df_residual_adj"].to_numpy(), want["df_residual_adj"].to_numpy()
    assert ((got_adj == 0) == (want_adj == 0)).all()
    close(f"{case} df_residual_adj", got_adj, want_adj, floor=1.0)
