"""edge_rust.run against production R on small designs the corpus does not cover.

Corpus-free: every input and reference lives in ``tests/edger_cases/<case>/``, generated by
``generate.R`` from MDFlexiComparisons ``runEdgeRPairwiseStats`` in the md-flexi-r45-local image
(edgeR 4.8.2). ``gap_zero`` and ``gap_tiny`` put df.prior inside (3, 50) with 3% of genes at
df.residual.adj = 0 and 3.4% at 0 < df.residual.adj < 0.01 (review r1, stats e); the rest are the
review's adversarial "matches edgeR" cases (empty group, singleton group, 1 residual df, 1 to 4
genes, dispersion capped at 4).
"""

from __future__ import annotations

import json
from pathlib import Path

import edge_rust
import numpy as np
import pandas as pd
import pytest

CASES_DIR = Path(__file__).parent / "edger_cases"
CASES = sorted(p.name for p in CASES_DIR.iterdir() if (p / "reference_output.csv").exists())
TOL = 1e-8


def load(case: str):
    d = CASES_DIR / case
    counts = pd.read_csv(d / "input_counts.csv", dtype={"id": str}).set_index("id")
    si = pd.read_csv(d / "input_sample_info.csv", dtype={"replicate": str, "condition": str})
    cmp = pd.read_csv(d / "input_comparisons.csv", dtype=str)
    params = json.loads((d / "params.json").read_text())
    return counts, si, cmp, params


def close(name: str, got: np.ndarray, want: np.ndarray, floor: float = 0.0):
    na_g, na_w = np.isnan(got), np.isnan(want)
    assert (na_g == na_w).all(), f"{name}: NA pattern differs at {np.flatnonzero(na_g != na_w)[:5]}"
    a, b = got[~na_w], want[~na_w]
    ok = np.abs(a - b) <= TOL * np.maximum(np.abs(b), floor)
    assert ok.all(), f"{name}: {a[~ok][:3]} vs {b[~ok][:3]}"


def test_cases_exist():
    assert {"gap_zero", "gap_tiny", "singleton", "zerogroup", "df1", "dispcap"} <= set(CASES)


@pytest.mark.parametrize("case", CASES)
def test_table_matches_production(case):
    counts, si, cmp, params = load(case)
    got = edge_rust.run(counts, si, cmp, params)
    want = pd.read_csv(CASES_DIR / case / "reference_output.csv")
    assert list(got.columns) == list(want.columns)
    assert (got["GroupId"].to_numpy() == want["GroupId"].to_numpy()).all()
    for c in want.columns[1:]:
        stat, _, label = c.partition(" ")
        g, w = got[c].to_numpy(dtype=float), want[c].to_numpy(dtype=float)
        if stat in ("stat", "SE", "CILeft", "CIRight"):
            # sqrt(F) carries half the relative error of F, and F below 1e-4 is checked at 1e-8
            # absolute (gaps there are ~1e-13), so the derived columns are checked where F >= 1e-4.
            keep = ~(np.abs(want[f"F {label}"].to_numpy(dtype=float)) < 1e-4)
            g, w = g[keep], w[keep]
        close(f"{case} {c}", g, w, floor=1.0 if stat == "F" else 0.0)


@pytest.mark.parametrize("case", CASES)
def test_df_matches_production(case):
    counts, si, cmp, params = load(case)
    _, diag = edge_rust.run(counts, si, cmp, params, diagnostics=True)
    want = pd.read_csv(CASES_DIR / case / "r_diag.csv", dtype={"id": str}).set_index("id")
    genes = diag["genes"]
    ids = list(genes["id"].astype(str))
    assert sorted(ids) == sorted(want.index)
    want = want.loc[ids]
    close(f"{case} df_prior", genes["df_prior"].to_numpy(), want["df_prior"].to_numpy())
    # df.residual.adj = 0 exactly where R has it, and within 1e-8 of 1 elsewhere.
    got_adj, want_adj = genes["df_residual_adj"].to_numpy(), want["df_residual_adj"].to_numpy()
    assert ((got_adj == 0) == (want_adj == 0)).all()
    close(f"{case} df_residual_adj", got_adj, want_adj, floor=1.0)
